version: "2.3"
services:
  bodypix:
    runtime: nvidia
    build:
      context: ./bodypix
      dockerfile: Dockerfile
    image: bodypix
    restart: always
    ports:
      - 9000:9000
    command: node /src/app.js
    devices:
      - /dev/nvidia0:/dev/nvidia0
  fakecam:
    build:
      context: ./fakecam
      dockerfile: Dockerfile
    image: fakecam
    restart: always
    links:
        - bodypix
    command: python fake.py
    environment:
      ACTUAL_CAMERA: "/dev/video0"
      FAKE_CAMERA: "/dev/video20"
      CAMERA_WIDTH: "1280"
      CAMERA_HEIGHT: "720"
      CAMERA_FPS: "30"
      BODYPIX_URL: http://bodypix:9000
      IS_VID_BACKGROUND: "true"
      BACKGROUND_FILE: "/data/background.mp4"
      #EFFECT: "hologram"
    volumes:
        - ./data:/data
    devices:
        - "/dev/video0:/dev/video0"
        - "/dev/video20:/dev/video20"
networks:
  fakecam:
    driver: bridge
